# Import all schemas for easy access
from app.schemas.admin_requests import (
    AnswerOptionCreateRequest,
    AnswerOptionUpdateRequest,
    BaseAdminRequest,
    CourseCreateRequest,
    CourseUpdateRequest,
    ModuleCreateRequest,
    ModuleReorderRequest,
    ModuleUpdateRequest,
    QuestionCreateRequest,
    QuestionUpdateRequest,
    TagCreateRequest,
    TagUpdateRequest,
    TestCreateRequest,
    TestUpdateRequest,
    UserRoleUpdateRequest,
)
from app.schemas.admin_responses import (
    AdminAnswerOptionResponse,
    AdminBulkOperationResponse,
    AdminCourseEnrollmentStats,
    AdminCourseListResponse,
    AdminCourseResponse,
    AdminModuleListResponse,
    AdminModuleResponse,
    AdminQuestionResponse,
    AdminStatsResponse,
    AdminTagResponse,
    AdminTestResponse,
    AdminUserListResponse,
    AdminUserResponse,
    BaseAdminResponse,
)
from app.schemas.requests import (
    BaseRequest,
    RefreshTokenRequest,
    TestAnswerRequest,
    TestSubmissionRequest,
    UserCreateRequest,
    UserLoginRequest,
    UserUpdatePasswordRequest,
)
from app.schemas.responses import (
    AccessTokenResponse,
    AnswerOptionResponse,
    CorrectAnswerResponse,
    ModuleTestStatusResponse,
    QuestionResponse,
    QuestionResultResponse,
    TestResponse,
    TestSubmissionResponse,
    UserResponse,
)

__all__ = [
    # Request schemas
    "BaseRequest",
    "RefreshTokenRequest",
    "TestAnswerRequest",
    "TestSubmissionRequest",
    "UserCreateRequest",
    "UserLoginRequest",
    "UserUpdatePasswordRequest",
    # Admin request schemas
    "BaseAdminRequest",
    "CourseCreateRequest",
    "CourseUpdateRequest",
    "ModuleCreateRequest",
    "ModuleUpdateRequest",
    "ModuleReorderRequest",
    "TestCreateRequest",
    "TestUpdateRequest",
    "QuestionCreateRequest",
    "QuestionUpdateRequest",
    "AnswerOptionCreateRequest",
    "AnswerOptionUpdateRequest",
    "TagCreateRequest",
    "TagUpdateRequest",
    "UserRoleUpdateRequest",
    # Response schemas
    "AccessTokenResponse",
    "AnswerOptionResponse",
    "CorrectAnswerResponse",
    "ModuleTestStatusResponse",
    "QuestionResultResponse",
    "QuestionResponse",
    "TestResponse",
    "TestSubmissionResponse",
    "UserResponse",
    # Admin response schemas
    "BaseAdminResponse",
    "AdminUserResponse",
    "AdminUserListResponse",
    "AdminTagResponse",
    "AdminAnswerOptionResponse",
    "AdminQuestionResponse",
    "AdminTestResponse",
    "AdminModuleResponse",
    "AdminModuleListResponse",
    "AdminCourseResponse",
    "AdminCourseListResponse",
    "AdminStatsResponse",
    "AdminBulkOperationResponse",
    "AdminCourseEnrollmentStats",
]
