"""add_idempotency_records_table

Revision ID: d14b5bc0ce36
Revises: b0584518c658
Create Date: 2025-12-27 10:19:11.930683

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd14b5bc0ce36'
down_revision = 'b0584518c658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_key',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('request_path', sa.String(length=512), nullable=False),
    sa.Column('request_method', sa.String(length=10), nullable=False),
    sa.Column('request_body_hash', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idempotency_key')
    # ### end Alembic commands ###
