"""fix refresh token FK

Revision ID: b26cbc146474
Revises: 70e5fe5e105c
Create Date: 2025-11-07 20:00:40.969046

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "b26cbc146474"
down_revision = "70e5fe5e105c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("refresh_token_user_id_fkey"), "refresh_token", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "refresh_token", "user", ["user_id"], ["UniqueID"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "refresh_token", type_="foreignkey")
    op.create_foreign_key(
        op.f("refresh_token_user_id_fkey"),
        "refresh_token",
        "user",
        ["user_id"],
        ["UniqueID"],
    )
    # ### end Alembic commands ###
