"""add_user_role_field

Revision ID: b0584518c658
Revises: b26cbc146474
Create Date: 2025-12-07 12:31:21.633629

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b0584518c658"
down_revision = "b26cbc146474"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("role", sa.String(length=50), nullable=False, server_default="user"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "role")
    # ### end Alembic commands ###
