"""add explanation to answer option

Revision ID: 70e5fe5e105c
Revises: c0ac19afae74
Create Date: 2025-11-06 16:25:52.833338

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "70e5fe5e105c"
down_revision = "c0ac19afae74"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("answer_option", sa.Column("explanation", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("answer_option", "explanation")
    # ### end Alembic commands ###
