"""fix_user_model_uniques

Revision ID: c0ac19afae74
Revises: a919c1bfabeb
Create Date: 2025-10-28 00:45:14.666751

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "c0ac19afae74"
down_revision = "a919c1bfabeb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=False)
    # ### end Alembic commands ###
