"""update_user_model

Revision ID: a919c1bfabeb
Revises: 5d50c741eac3
Create Date: 2025-10-27 16:50:09.752033

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "a919c1bfabeb"
down_revision = "5d50c741eac3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    # ### end Alembic commands ###
